config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'

  get 'pages/aboutus'
  get 'pages/contactus'
  get 'pages/professionalservices'
  get 'pages/products'
  get 'pages/solutions'
  get 'pages/pricing'
  get 'pages/pvm'
  get 'pages/wso2is'
  get 'pages/jira'

#  root :to => redirect('/')
  root :to => 'welcome#index'
  devise_for :users
  resources :pvprovisions
  resources :pvcrequests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

#      can :access, :rails_admin   # grant access to rails_admin
#      can :dashboard              # grant access to the dashboard
#      user ||= User.new # guest user
#      if user.role == 'admin'
       if user.admin
         can :access, :rails_admin       # only allow admin users to access Rails Admin
         can :dashboard          
       end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all   
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pvcrequest.rb
class Pvcrequest < ApplicationRecord
end

app/models/pvprovision.rb
class Pvprovision < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  add_breadcrumb "home", :root_path
#  load_and_authorize_resource
#  check_authorization
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
#  add_breadcrumb "my", :my_path

  def index
    # ...
    #
        add_breadcrumb "index", index_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, :except => [:aboutus, :professionalservices]
#  before_action :authenticate_user!, :except => [:professionalservices]
  skip_before_action :authenticate_user!, :except => [:pricing]
  skip_before_action :authenticate_user!, :except => [:jira]
  skip_before_action :authenticate_user!, :except => [:wso2is]
  def solutions
    add_breadcrumb "Solutions", pages_solutions_path
  end

  def professionalservices
    add_breadcrumb "Professional Services", pages_professionalservices_path
  end

  def aboutus
    add_breadcrumb "About Us", pages_aboutus_path
  end

  def contactus
    add_breadcrumb "Contact Us", pages_contactus_path
  end

  def pricing
    add_breadcrumb "Pricing", pages_pricing_path
  end

  def jira
    add_breadcrumb "Atlassian Jira", pages_jira_path
  end

  def wso2is
    add_breadcrumb "WSO2 Identity Server", pages_wso2is_path
  end

  def info
  end
end

app/controllers/pvcrequests_controller.rb
class PvcrequestsController < ApplicationController
  before_action :set_pvcrequest, only: [:show, :edit, :update, :destroy]

  # GET /pvcrequests
  # GET /pvcrequests.json
  def index
    @pvcrequests = Pvcrequest.all
  end

  # GET /pvcrequests/1
  # GET /pvcrequests/1.json
  def show
  end

  # GET /pvcrequests/new
  def new
    @pvcrequest = Pvcrequest.new
  end

  # GET /pvcrequests/1/edit
  def edit
  end

  # POST /pvcrequests
  # POST /pvcrequests.json
  def create
    @pvcrequest = Pvcrequest.new(pvcrequest_params)

    respond_to do |format|
      if @pvcrequest.save
        format.html { redirect_to @pvcrequest, notice: 'Pvcrequest was successfully created.' }
        format.json { render :show, status: :created, location: @pvcrequest }
      else
        format.html { render :new }
        format.json { render json: @pvcrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pvcrequests/1
  # PATCH/PUT /pvcrequests/1.json
  def update
    respond_to do |format|
      if @pvcrequest.update(pvcrequest_params)
        format.html { redirect_to @pvcrequest, notice: 'Pvcrequest was successfully updated.' }
        format.json { render :show, status: :ok, location: @pvcrequest }
      else
        format.html { render :edit }
        format.json { render json: @pvcrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pvcrequests/1
  # DELETE /pvcrequests/1.json
  def destroy
    @pvcrequest.destroy
    respond_to do |format|
      format.html { redirect_to pvcrequests_url, notice: 'Pvcrequest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pvcrequest
      @pvcrequest = Pvcrequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pvcrequest_params
      params.fetch(:pvcrequest, {})
    end
end

app/controllers/pvprovisions_controller.rb
class PvprovisionsController < ApplicationController
  before_action :set_pvprovision, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "pvprovisions", "/pvprovisions"
#  load_and_authorize_resource

  # GET /pvprovisions
  # GET /pvprovisions.json
  def index
    @pvprovisions = Pvprovision.all
  end

  # GET /pvprovisions/1
  # GET /pvprovisions/1.json
  def show
  end

  # GET /pvprovisions/new
  def new
    @pvprovision = Pvprovision.new
  end

  # GET /pvprovisions/1/edit
  def edit
  end

  # POST /pvprovisions
  # POST /pvprovisions.json
  def create
    @pvprovision = Pvprovision.new(pvprovision_params)

    respond_to do |format|
      if @pvprovision.save
        format.html { redirect_to @pvprovision, notice: 'Pvprovision was successfully created.' }
        format.json { render :show, status: :created, location: @pvprovision }
      else
        format.html { render :new }
        format.json { render json: @pvprovision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pvprovisions/1
  # PATCH/PUT /pvprovisions/1.json
  def update
    respond_to do |format|
      if @pvprovision.update(pvprovision_params)
        format.html { redirect_to @pvprovision, notice: 'Pvprovision was successfully updated.' }
        format.json { render :show, status: :ok, location: @pvprovision }
      else
        format.html { render :edit }
        format.json { render json: @pvprovision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pvprovisions/1
  # DELETE /pvprovisions/1.json
  def destroy
    @pvprovision.destroy
    respond_to do |format|
      format.html { redirect_to pvprovisions_url, notice: 'Pvprovision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pvprovision
      @pvprovision = Pvprovision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pvprovision_params
      params.fetch(:pvprovision, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pvcrequests_helper.rb
module PvcrequestsHelper
end

app/helpers/pvprovisions_helper.rb
module PvprovisionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <div class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </div>
  <% if ContactUs.require_subject %>
    <div class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </div>
  <div class='commit'>
    <%= f.submit :submit, :class => 'submit create', :title => t('.submit'), :value => t('.submit') %>
  </div>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/pages/aboutus.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About Eupraxia Labs</title>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>
    <%= javascript_include_tag params[:controller] %>
  </head>
  <body>

    <h2 style="border: 4px solid rgb(204, 204, 204); background-color: lightgrey; padding: 5px 10px; text-align: center;"><strong><span style="color: #226389;">Company Background</span></strong></h2>


    <p>Based in Austin, Texas<strong> Eupraxia Labs, LLC</strong> is focused on the newest wave of innovation in the private data center: <strong>Open Source Web-Scale Information Technology (IT)</strong>.</p>

    <p><strong>Web-scale IT</strong> is a pattern of global-class computing that delivers the capabilities of large <strong>Cloud Service Providers (CSP)</strong> within an <strong>enterprise information technology (EIT)</strong> setting. <strong>Web-scale IT-enablement</strong> products and services are increasing in demand year-over-year. More organizations will begin thinking, acting, and building applications and infrastructures like the Web giants: Amazon, Google, SalesForce, and Facebook. <strong>Web-scale IT</strong> does not happen at the flip of a switch. The methodologies and processes to achieve this capability are rapidly evolving.</p>

    <p>Commercial hardware platforms are embracing the new models and cloud-optimized and software-defined approaches, such as <strong>Software-Defined Networking (SDN)</strong> and <strong>Software-Defined Storage (SDS)</strong> are reaching mainstream. <strong>Eupraxia Labs</strong> provides open source software and professional services to enable companies to implement, manage, and operate a <strong>Cloud Management Platform (CMP)</strong> in support of their own business applications and those of their partners and customers.</p>

    <p>In those cases where companies choose to outsource the cloud management and operations (<strong>MANO</strong>) functions, <strong>Eupraxia Labs</strong> provides that support on an ongoing basis. The open source solutions, offered by <strong>Eupraxia Labs</strong>, significantly reduces the barrier-to-entry cost for <strong>small-to-medium sized businesses (SMB)</strong> and optimizes the cost structure for <strong>large enterprises</strong>.</p>

    <p>The underlying operating system for all applications is the premier open source equivalent to <strong>Red Hat Enterprise Linux (RHEL), CentOS</strong>. The Cloud Management Platorm (<strong>CMP</strong>), Infrastructure-as-a-Service (<strong>IaaS</strong>), and Platform-as-a-Service (<strong>PaaS</strong>) are all open source upstreams to Red Hat&#39;s commercial counterparts.</p>

    <p>&nbsp;</p>

    <p style="text-align: center;">&nbsp;</p>
  </body>
</html>

app/views/pages/contactus.html.erb
<h2>Put in a contact form with recaptcha</h2>

app/views/pages/jira.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blueprint:Atlassian Jira</title>
    <%= csrf_meta_tags %>
    <!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.css">
    -->
    <!-- <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>
    <%= javascript_include_tag params[:controller] %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>
<style type="text/css">

.jumbotron {
    position: relative;
    background: #696767 url("/assets/chinalakeDesert-1260x945.png") center center;
    width: 100%;
    height: 100%;
    background-size: cover;
    overflow: hidden;
}
#jumbo {
  padding: 100px;
}

/* Container Border */
#smallcontainer1 {
	border: 2px solid #696767;
  display: table;
  height: 400px;
  width: 30%;
	border-radius: 2px;
	margin-top: 2px;
  margin-left: 2px;
  margin-right: 2px;
	margin-bottom: 2px;
}

#smallcontainer2 {
	border: 2px solid #226389;
  display: table;
  height: 400px;
  width: 30%;
	border-radius: 2px;
	margin-top: 2px;
  margin-left: 2px;
  margin-right: 2px;
	margin-bottom: 2px;
}

#smallcontainer3 {
	border: 2px solid #696767;
  display: table;
  height: 400px;
  width: 30%;
	border-radius: 2px;
	margin-top: 2px;
  margin-left: 2px;
  margin-right: 2px;
	margin-bottom: 2px;
}
.btn-primary {
  background-color: #696767 !important;
  color: white !important;
  }

.dropdown-large {
  position: static !important;
}
.dropdown-menu-large {
  margin-left: 16px;
  margin-right: 16px;
  padding: 20px 0px;
}
.dropdown-menu-large > li > ul {
  padding: 0;
  margin: 0;
}
.dropdown-menu-large > li > ul > li {
  list-style: none;
}
.dropdown-menu-large > li > ul > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.428571429;
  color: #333333;
  white-space: normal;
}
.dropdown-menu-large > li ul > li > a:hover,
.dropdown-menu-large > li ul > li > a:focus {
  text-decoration: none;
  color: #262626;
  background-color: #f5f5f5;
}
.dropdown-menu-large .disabled > a,
.dropdown-menu-large .disabled > a:hover,
.dropdown-menu-large .disabled > a:focus {
  color: #999999;
}
.dropdown-menu-large .disabled > a:hover,
.dropdown-menu-large .disabled > a:focus {
  text-decoration: none;
  background-color: transparent;
  background-image: none;
  filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
  cursor: not-allowed;
}
.dropdown-menu-large .dropdown-header {
  color: white;
  font-size: 18px;
}
@media (max-width: 768px) {
  .dropdown-menu-large {
    margin-left: 0 ;
    margin-right: 0 ;
  }
  .dropdown-menu-large > li {
    margin-bottom: 30px;
  }
  .dropdown-menu-large > li:last-child {
    margin-bottom: 0;
  }
  .dropdown-menu-large .dropdown-header {
    padding: 3px 15px !important;
  }
}

body {
  padding-top: 120px;
  font-family: "Open Sans", sans-serif;
  font-size: 14px;
}

</style>
<body>
<nav class="navbar navbar-default navbar-static">
    <div class="navbar-header">
		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Eupraxia Labs</a>
	</div>


	<div class="collapse navbar-collapse js-navbar-collapse">
		<ul class="nav navbar-nav">
			<li class="dropdown dropdown-large">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Products</b></a>
				<ul class="dropdown-menu dropdown-menu-large row">
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Cloud Management</li>
              <li><%=link_to "Blueprint: EL Persistent Volume Manager (OpenShift 3)", pvprovisions_path %></li>
							<li><a href="#">ManageIQ</a></li>
							<li><a href="#">Examples</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Identity Management and Security</li>
							<li><a href="#">CyberSAFE</a></li>
							<li><%=link_to "Blueprint:WSO2 Identity Server (OpenShift 3)", pages_wso2is_path %></li>
							<li><a href="#">Blueprint:Shibboleth IdP</a></li>
							<li><a href="#">Blueprint: OpenVAS</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Continuous Integration</li>
							<li><a href="#">Basic example</a></li>
							<li><a href="#">Button toolbar</a></li>
							<li><a href="#">Sizing</a></li>
							<li><a href="#">Nesting</a></li>
							<li><a href="#">Vertical variation</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Customer Relationship Management</li>
							<li><a href="#">Single button dropdowns</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Content Management Systems</li>
							<li><a href="#">Basic example</a></li>
							<li><a href="#">Sizing</a></li>
							<li><a href="#">Checkboxes and radio addons</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Storage Management</li>
							<li><a href="#">GlusterFS</a></li>
							<li><a href="#">Ceph</a></li>
							<li><a href="#">OCFS</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Enterprise File Sync and Share (EFSS)</li>
							<li><a href="#">Default navbar</a></li>
							<li><a href="#">Buttons</a></li>
							<li><a href="#">Text</a></li>
							<li><a href="#">Non-nav links</a></li>
							<li><a href="#">Component alignment</a></li>
							<li><a href="#">Fixed to top</a></li>
							<li><a href="#">Fixed to bottom</a></li>
							<li><a href="#">Static top</a></li>
							<li><a href="#">Inverted navbar</a></li>
						</ul>
					</li>
				</ul>

			</li>
		</ul>

	</div><!-- /.nav-collapse -->
</nav>

<div id="jumbo" class="jumbotron">
    <div class="container">
        <img src="/assets/Eupraxia_Logo_2C_RGB-300x41.png">
        <img src="/assets/atlassian-rgb-navy-medium.png" width="300" height="79">
        <img src="/assets/large_v-dark-trans.png" width="250" height="218">
    </div>
</div>

<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div id="smallcontainer1" class="col-md-4">
          <h2><center>OpenShift 3</center></h2>
          <p>Lots to talk about here. More and more and more and more and more</p>
          <p><a class="btn btn-primary btn-sm" href="#" role="button" background-color= #226389>More &raquo;</a></p>
        </div>
        <div id="smallcontainer2" class="col-md-4">
          <img src="/assets/atlassian-rgb-navy-medium.png" width="200" height="55">
          <h2>Atlassian Jira</h2>
          <p>Dockerized and OpenShifterized</p>
          <p><a class="btn btn-default" href="#" role="button">More &raquo;</a></p>
       </div>
        <div id="smallcontainer3" class="col-md-4">
          <h2>OpenStack Cloud</h2>
          <p>Manage your Infrastructure-as-a-Service (IaaS).</p>
          <p><a class="btn btn-default" href="#" role="button">More &raquo;</a></p>
        </div>

      </div>
</body>
</html>

app/views/pages/pricing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eupraxia Labs Pricing</title>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>
    <%= javascript_include_tag params[:controller] %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <h2>Put in matrix: Community, Bronze, Silver, Gold, Platinum</h2>
  </body>
</html>

app/views/pages/products.html.erb
<h1> Lots to put in Here ...... </h1>

app/views/pages/professionalservices.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blueprint:IdM-WSO2</title>
        <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>
    <%= javascript_include_tag params[:controller] %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>
  <body>
    <h1>Pages#professionalservices</h1>
    <p>Find me in app/views/pages/professionalservices.html.erb</p>
    <h2> This is about Eupraxia Labs' Professional Services </h2>
  </body>
</html>

app/views/pages/pvm.html.erb
<style type="text/css">

.jumbotron {
    position: relative;
    background: #696767 url("/assets/chinalakeDesert-1260x945.png") center center;
        width: 100%;
    height: 100%;
    background-size: cover;
    overflow: hidden;
}
#jumbo {
  padding: 100px;
}
</style>

<div id="jumbo" class="jumbotron">
    <div class="container">
            <img src="/assets/powered_by_openshift"
              <p>...</p>
    </div>
</div>

<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2><center>OpenShift 3</center></h2>
          <p>Lots to talk about here. More and more and more and more and more</p>
          <p><a class="btn btn-default" href="#" role="button">More &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Docker Cloud</h2>
          <p>Set up a world class hybrid cloud.</p>
          <p><a class="btn btn-default" href="#" role="button">More &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Gluster Distributed File System</h2>
          <p>GlusterFS for your Private Cloud</p>
          <p><a class="btn btn-default" href="#" role="button">More &raquo;</a></p>
        </div>

        
      </div>

app/views/pvcrequests/edit.html.erb
<h1>Editing Pvcrequest</h1>

<%= render 'form', pvcrequest: @pvcrequest %>

<%= link_to 'Show', @pvcrequest %> |
<%= link_to 'Back', pvcrequests_path %>

app/views/pvcrequests/new.html.erb
<h1>New Pvcrequest</h1>

<%= render 'form', pvcrequest: @pvcrequest %>

<%= link_to 'Back', pvcrequests_path %>

app/views/pvcrequests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pvcrequest_path(@pvcrequest) %> |
<%= link_to 'Back', pvcrequests_path %>

app/views/pvprovisions/edit.html.erb
<h1>Editing Pvprovision</h1>

<%= render 'form', pvprovision: @pvprovision %>

<%= link_to 'Show', @pvprovision %> |
<%= link_to 'Back', pvprovisions_path %>

app/views/pvprovisions/new.html.erb
<h1>New Pvprovision</h1>

<%= render 'form', pvprovision: @pvprovision %>

<%= link_to 'Back', pvprovisions_path %>

app/views/pvprovisions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_pvprovision_path(@pvprovision) %> |
<%= link_to 'Back', pvprovisions_path %>